# Generated by Django 5.2.7 on 2025-10-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
